version: "3.7"

services:
  node:
    container_name: node
    build:
      context: ./node
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./node:/home/node
      - ./node/tsconfig.json:/home/node/tsconfig.json
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "9229:9229"
    env_file:
      - ./node/.env

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: "always"
    env_file:
      - ./client/.env
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - ./client/:/client/

networks:
  testnet:
    driver: bridge
